Build, and push new Dockerimage:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  script:
    - docker image build --tag "${CI_REGISTRY_IMAGE}:latest" .
    - docker image push "${CI_REGISTRY_IMAGE}:latest"

Tell the server:
  stage: deploy
  image: alpine:latest
  before_script:
    - chmod 0400 "${DEPLOY_KEY}" "${DEPLOY_HOST_KEYS}"
    - apk add openssh-client
  script:
    - ssh -i "${DEPLOY_KEY}" -o UserKnownHostsFile="${DEPLOY_HOST_KEYS}" deploy@"${DEPLOY_HOST}"
